language: bash
env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH
  - secure: mss3Beb1yjHURyMP6RKJONOusLZDZXEX9onQbV38rlDoq2kcUMX236I1u9KWCPen8SIksciuNexteJHWc7Lcn9hIr6ZPNW8TBKyZIo7YyJC7Ck+q5sPAatZIOVrI8SFQLO62D0L9AThFrtTziu0yBtkygRCWCl0X1VwcBfWWrVzhZfoFsDIXOZpIRI0uZ9/+QuMImcJ4FsYGdQvULyp9c06eHDRVh0jgU95u0GqDousXdpWQeblm8qxXwRZM/v0yyHbGG2mTRKOrqfZXJFN4mobWtPq7IrnbWMxkrZajaiiJ+2Zh98IsTC3BlRxWhaTAJgHXnpGydT1inSfUh/RB+78ljjxk2nME8jO/xrpQ8OWERozxAnEc56F1VWK7VfxEASpVPN2JTDYr3PeNoK/Bx6D7XNiK3SzQzIr3W8OyVsQhCafROQpepODLedq0HJqUbTXVXiWmECs8SjcuUsM1Yxp8jk0nu+x+Wh7QG8x3MvPrZpy6ZDgl8xjZg6jD84K7SzVmD8kd0SxRT02CSMCyKvrev/V7d6kxGRJrqMWA8ZMdRus/1dc9vlfH3AE4p42wAWPYnMWQwMKbL2OcY2CFGu8mfzqH8dfpecmk4hhhKdvuJ2ujoHOa2OV6WVxfRG3LtgXQzQ6GSvqwzan5vskQcwOGKwdmNrj3bqN+j/T9uTM=
  - secure: WVJj1nXDtO3swtYVbb0WMrEeCKHwsb7iTlyS1cT2SkDtOQ1+DhJbKukMmASs9sjnITNOfJdJzyMQTdoQqS8KIjjqowe1crLyZxsdHCmJRpYp7OOE7WP1Q7OwFTWCuBMDuv3T4xsowrlIexNbVSiPPKdrP7CC5PFTIkC/LuIpCHx9UpVNEjvFMgecw2XzXWjuw6/yQBlwFWAvrowfuuyE+im0NU8O/C7PV5wtcFMRIaVAepdncc3DMMzGO4x1exSTXMh0OWrDU5/K2Vyavos6Kp7O/D9ii4Jp2VNpOjTzttJ/h12mUyTBeFqWjJqXQDQWu9FopcbkKt6ghMbq8N4W7ePsAOzOY5IikFk2NFNpf6yTqwWFUlc0zeRwcGSVpG3ip/OYISrgVCL43N4H+JtcpyZVsboX3ecjFR2/GUy4pY2A7Flt9X5kWP7/IOyLJ7aSM9Ybfn0LVvCLC1y9yK1abJOYXkRTPbe8H1EOysHjBY2Oo2YaX7DbCI5u325fLF3zfzNtNYEO4cMMpU3DRJbMc04xRCb0GXCclTDX4UhUW/488iPk5GL65E0+vZu4jcCuR0J8XNHbVcniwBjhSgGQhdq4UpKzZWjpoTzL7AJrG9NFjBzeVvfRlygdcBhX2jMWZGV2G3lIotGjKo5ie4H6QzPOrL8DgbR4p/EVhLjXfiM=
before_install:
- wget https://github.com/jgm/pandoc/releases/download/1.15.0.5/pandoc-1.15.0.5-1-amd64.deb
  && ar p pandoc-1.15.0.5-1-amd64.deb data.tar.gz | tar zx
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
- sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install texlive-science texlive-humanities
script:
- cd document && make manuscript-biorxiv.pdf
after_success:
- bash push.sh
